/**
 * Draws the favicon: the حص mark struck on a coin.
 *
 *   node scripts/make-favicon.mjs
 *
 * Two revisions got here. It began as the money box itself, traced from the scan's
 * own silhouette — accurate, and at the 16px a favicon is actually shown at,
 * unreadable: a hollow ovoid with a nub, which is a lamp or a vase or nothing. It
 * became a plain milled coin, which reads at every size but says nothing about
 * Hasaleh in particular. This is both: the coin carries the shape, and the drawn
 * mark from `hasaleh media/hasaleh favicon.png` carries the identity.
 *
 * One path, `fill-rule: evenodd`, so the coin and the mark punched out of it are a
 * single silhouette that works on any background — which a favicon has to, because
 * it sits in browser chrome and cannot assume the paper behind it.
 *
 * Colour comes out of app/globals.css rather than being restated here.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { traceBitmap, loopsToPath } from './lib/trace-bitmap.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const CSS = path.join(ROOT, 'app', 'globals.css');
const SOURCE = path.resolve(ROOT, '..', 'hasaleh media', 'hasaleh favicon.png');
const OUTPUT = path.join(ROOT, 'app', 'icon.svg');

/**
 * Reads a colour token out of globals.css rather than restating it here. These were
 * hardcoded once and silently kept the old brand colour through a palette change,
 * so the favicon stopped matching the site.
 */
function token(name) {
  const css = fs.readFileSync(CSS, 'utf8');
  const match = new RegExp(`--${name}:\\s*(#[0-9a-fA-F]{3,8})\\s*;`).exec(css);
  if (!match) throw new Error(`--${name} not found in app/globals.css`);
  return match[1];
}

const MARK = token('mark');
const MARK_ON_DARK = token('mark-on-dark');

/** SVG viewBox, square. */
const BOX = 32;
const CENTRE = BOX / 2;

/** Outer radius, leaving a hair of margin so the milling is not clipped. */
const RADIUS = 15;
/**
 * Milled edge — the reeding round the rim of a struck coin, and the one cue that
 * separates a coin from a dot without spending any interior detail on it.
 *
 * Shallow and frequent, which took some finding. The first attempt used 14 reeds
 * 1.5 deep, and at any size the notches read as gear teeth: a cog, not a coin.
 * Below about a unit of depth they stop being teeth and become milling. At 16px the
 * reeds fall under a device pixel each and average back into a slightly soft edge,
 * which is the correct failure — it degrades to a plain disc rather than to a
 * sprocket.
 */
const REEDS = 24;
const REED_DEPTH = 0.8;
/** Fraction of each reed's period that is cut away. */
const REED_DUTY = 0.5;
/** Points along each uncut arc. Enough that the rim between notches stays round. */
const ARC_STEPS = 4;

/**
 * Width of the struck mark, in viewBox units.
 *
 * The drawing is about 1.67 times wider than it is tall, so width is what binds. At
 * 24 it reaches past the notch floor and eats into the milling, which reads as a
 * broken rim rather than a struck face. 22 leaves a little over 3 units of clearance
 * inside the reeding, and that is the constraint — not the look of the mark itself.
 */
const MARK_WIDTH = 22;
/**
 * Simplification tolerance for the mark, in viewBox units — so it is stated in terms
 * of the size the thing is actually drawn at. 0.16 of 32 units is about a twelfth of
 * a device pixel at 16px, and it takes the trace from 2612 points to 48.
 */
const MARK_TOLERANCE = 0.16;

const point = (angle, radius) =>
  `${(CENTRE + Math.cos(angle) * radius).toFixed(2)} ${(CENTRE + Math.sin(angle) * radius).toFixed(2)}`;

/** The milled rim, walked as one closed polygon: arc, notch, arc, notch. */
function milledRim() {
  const period = (Math.PI * 2) / REEDS;
  const cut = period * REED_DUTY;
  const flat = period - cut;
  const points = [];

  for (let reed = 0; reed < REEDS; reed++) {
    const start = reed * period;
    for (let step = 0; step <= ARC_STEPS; step++) {
      points.push(point(start + (flat * step) / ARC_STEPS, RADIUS));
    }
    // Straight in, across the notch floor, and straight back out.
    points.push(point(start + flat, RADIUS - REED_DEPTH));
    points.push(point(start + flat + cut, RADIUS - REED_DEPTH));
  }

  return `M${points.join('L')}Z`;
}

const traced = await traceBitmap(SOURCE, { minLoopArea: 20 });
const mark = loopsToPath(traced.loops, traced.bbox, {
  targetWidth: MARK_WIDTH,
  centre: [CENTRE, CENTRE],
  tolerance: MARK_TOLERANCE,
  precision: 2,
});

// Disc first, mark second. Under evenodd the mark's outer contours land inside the
// disc and so become holes, and any counter inside them flips back to ink — which is
// exactly how a struck letter behaves.
const d = `${milledRim()}${mark.d}`;

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${BOX} ${BOX}">
  <!-- Generated by scripts/make-favicon.mjs: a milled coin with the drawn حص mark
       from "hasaleh media/hasaleh favicon.png" struck out of it with evenodd.
       Do not hand-edit. -->
  <style>
    /* A favicon sits in browser chrome, not on the page, so it cannot assume the
       paper behind it. The ink disappears against a dark toolbar, so a lighter tint
       takes over there. Both come from globals.css. */
    .coin { fill: ${MARK}; }
    @media (prefers-color-scheme: dark) {
      .coin { fill: ${MARK_ON_DARK}; }
    }
  </style>
  <title>حصالة</title>
  <path class="coin" fill="${MARK}" fill-rule="evenodd" d="${d}"/>
</svg>
`;

fs.writeFileSync(OUTPUT, svg);
console.log(`coin: r${RADIUS}, ${REEDS} reeds ${REED_DEPTH} deep`);
console.log(
  `mark: ${traced.loops.length} loops, ${traced.tracedPoints} points -> ${mark.points}, ` +
    `${MARK_WIDTH}x${mark.height.toFixed(1)} units`,
);
console.log(`wrote app/icon.svg  ${svg.length} bytes  (fill ${MARK}, dark ${MARK_ON_DARK})`);
