/**
 * Traces the drawn brand marks into vector outlines.
 *
 *   node scripts/make-marks.mjs
 *
 * Two marks, both brush drawings, both used in the masthead:
 *
 *   حصالة       the sub-brand wordmark, from `hasaleh media/`
 *   the sun     Zawyeh's own mark, from the shared `zawyeh space/media/`
 *
 * The sun deliberately reaches across the sub-brand boundary rather than being
 * copied in. It belongs to the parent brand and every Zawyeh property draws the same
 * file; a local copy is how two Zawyehs end up on one website.
 *
 * Neither bitmap could be used directly. Both sit at around 30px in the masthead, and
 * both have to take their colour from `--mark` like every other stroke on the page.
 * So each is traced to a path and emitted into `public/`, and the masthead uses them
 * as CSS masks over `currentColor` — the shape comes from the asset, the colour from
 * the cascade, and the two cannot drift apart.
 *
 * The tracing itself lives in scripts/lib/trace-bitmap.mjs, shared with the favicon.
 *
 * Idempotent. Re-run if either drawing is redrawn.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { traceBitmap, loopsToPath } from './lib/trace-bitmap.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');

/**
 * `viewWidth` is the width each outline is normalised to, and `tolerance` is the
 * Douglas-Peucker tolerance **in those same units** — so it reads as "how far off may
 * this be, relative to how big it is drawn", independent of the source resolution.
 *
 * The two tolerances differ because the sources do. The logo is 1367px wide and the
 * sun only 257px, so the same visual tolerance is a very different number of source
 * pixels: below about 4 units the sun's trace is finer than its own pixel staircase
 * and simplifies almost nothing (1327 points, 15 KB). At 4 it is 225 points and 2.6
 * KB and indistinguishable at 200px, let alone the ~34px it is drawn at. Past about
 * 9 the long lower-left ray visibly facets.
 */
const MARKS = [
  {
    name: 'wordmark',
    source: path.resolve(ROOT, '..', 'hasaleh media', 'hasaleh logo.png'),
    output: path.join(ROOT, 'public', 'wordmark.svg'),
    title: 'حصالة',
    viewWidth: 1000,
    tolerance: 1.1,
    minLoopArea: 24,
  },
  {
    name: 'zawyeh-sun',
    source: path.resolve(ROOT, '..', '..', 'media', 'zawyeh-sun.png'),
    output: path.join(ROOT, 'public', 'zawyeh-sun.svg'),
    title: 'زاوية',
    viewWidth: 1000,
    tolerance: 4,
    // The sun has two small detached strokes above the core that are part of the
    // drawing, not specks, so the floor has to sit below them.
    minLoopArea: 12,
  },
];

for (const mark of MARKS) {
  const traced = await traceBitmap(mark.source, { minLoopArea: mark.minLoopArea });
  const outline = loopsToPath(traced.loops, traced.bbox, {
    targetWidth: mark.viewWidth,
    tolerance: mark.tolerance,
    precision: 1,
  });

  // Rounded, because a fractional viewBox height would put the mask on a half-pixel.
  const viewHeight = Math.round(outline.height);

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${mark.viewWidth} ${viewHeight}">
  <!-- Generated by scripts/make-marks.mjs from "${path.basename(mark.source)}".
       The outline is the drawing's own pixel boundary, simplified. Do not hand-edit.

       No colour is stated here on purpose: the masthead uses this file as a CSS
       mask over currentColor, so the mark inherits the ink token along with the rest
       of the page and cannot drift from it. (A double hyphen is illegal inside an
       XML comment, which is why the token is not named here.) -->
  <title>${mark.title}</title>
  <path fill="#000" fill-rule="evenodd" d="${outline.d}"/>
</svg>
`;

  fs.writeFileSync(mark.output, svg);

  const { minX, minY, maxX, maxY } = traced.bbox;
  const inkWidth = maxX - minX + 1;
  const inkHeight = maxY - minY + 1;
  console.log(
    `${mark.name}: source ${traced.width}×${traced.height}, ink ${inkWidth}×${inkHeight}, ` +
      `${traced.loops.length} loops, ${traced.tracedPoints} -> ${outline.points} points`,
  );
  console.log(
    `  wrote ${path.relative(ROOT, mark.output)}  ${svg.length} bytes  ` +
      `viewBox 0 0 ${mark.viewWidth} ${viewHeight}  (aspect ${(mark.viewWidth / viewHeight).toFixed(3)})`,
  );
}
