/**
 * Derives the favicon from the actual scan.
 *
 *   node scripts/make-favicon.mjs
 *
 * The Hasaleh is a body of revolution about Y, which means its silhouette is
 * fully determined by the maximum radius at each height. So rather than drawing an
 * approximation by hand, this reads public/hasaleh.mesh, measures r(y), and emits
 * the exact profile mirrored about the axis as app/icon.svg.
 *
 * Re-run after `npm run model`.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const MESH = path.join(ROOT, 'public', 'hasaleh.mesh');
const OUTPUT = path.join(ROOT, 'app', 'icon.svg');

/**
 * Height bands. Fewer than the mesh could give: a favicon lives at 16-32px, where
 * extra profile detail turns into noise rather than shape.
 */
const BANDS = 26;
/** SVG viewBox is square; the profile is fitted into this with a margin. */
const BOX = 32;
const MARGIN = 1.5;
/**
 * Deliberately heavy. At 16px a 2.1 stroke renders about one device pixel and the
 * outline all but vanishes; this reads at every size a favicon is actually shown.
 */
const STROKE = 3;
/** Passes of neighbour averaging, to take the scan's jitter out of the outline. */
const SMOOTHING_PASSES = 2;

function readMesh(file) {
  const buffer = fs.readFileSync(file);
  const magic = buffer.toString('ascii', 0, 4);
  if (magic !== 'HSLH') throw new Error('not a Hasaleh mesh');
  const version = buffer.readUInt32LE(4);
  if (version !== 2) throw new Error(`unsupported mesh version ${version}`);
  const vertexCount = buffer.readUInt32LE(8);

  // Copy out, because the Buffer's byteOffset is not guaranteed 4-byte aligned.
  const positions = new Float32Array(vertexCount * 3);
  for (let i = 0; i < positions.length; i++) {
    positions[i] = buffer.readFloatLE(64 + i * 4);
  }
  return positions;
}

const positions = readMesh(MESH);

let yMin = Infinity;
let yMax = -Infinity;
for (let i = 1; i < positions.length; i += 3) {
  if (positions[i] < yMin) yMin = positions[i];
  if (positions[i] > yMax) yMax = positions[i];
}

// Maximum radius from the Y axis within each height band.
const radii = new Array(BANDS).fill(0);
for (let i = 0; i < positions.length; i += 3) {
  const x = positions[i];
  const y = positions[i + 1];
  const z = positions[i + 2];
  let band = Math.floor(((y - yMin) / (yMax - yMin)) * BANDS);
  if (band >= BANDS) band = BANDS - 1;
  const r = Math.hypot(x, z);
  if (r > radii[band]) radii[band] = r;
}

// Scan noise can leave a band short; lift any band below both neighbours.
for (let i = 1; i < BANDS - 1; i++) {
  const floor = Math.min(radii[i - 1], radii[i + 1]);
  if (radii[i] < floor * 0.82) radii[i] = floor * 0.82;
}

// Then soften the polyline. The silhouette of a turned object is smooth; the
// jitter left in it is measurement error, and it reads as fuzz at small sizes.
for (let pass = 0; pass < SMOOTHING_PASSES; pass++) {
  const copy = [...radii];
  for (let i = 1; i < BANDS - 1; i++) {
    radii[i] = (copy[i - 1] + copy[i] * 2 + copy[i + 1]) / 4;
  }
}

const maxRadius = Math.max(...radii);
const inner = BOX - MARGIN * 2;
// One scale for both axes, so the icon keeps the object's real proportions.
const scale = Math.min(inner / (maxRadius * 2), inner / (yMax - yMin));
const cx = BOX / 2;
const height = (yMax - yMin) * scale;
const top = (BOX - height) / 2;

const px = (r) => cx + r * scale;
const py = (band) => top + height - ((band + 0.5) / BANDS) * height;

// Up the right-hand profile, then back down the mirrored left-hand side.
const right = radii.map((r, i) => `${px(r).toFixed(2)} ${py(i).toFixed(2)}`);
const left = radii
  .map((r, i) => `${px(-r).toFixed(2)} ${py(i).toFixed(2)}`)
  .reverse();

const d = `M ${right[0]} L ${right.slice(1).join(' L ')} L ${left.join(' L ')} Z`;

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${BOX} ${BOX}">
  <!-- Generated by scripts/make-favicon.mjs from public/hasaleh.mesh.
       The outline is the scan's own profile, measured as max radius per height
       band and mirrored about the axis of revolution. Do not hand-edit. -->
  <style>
    /* A favicon sits in browser chrome, not on the page, so it cannot assume a
       white ground. The deep brand green disappears against a dark toolbar;
       a lighter emerald keeps the outline legible there. */
    .hasaleh { stroke: #046b4a; }
    @media (prefers-color-scheme: dark) {
      .hasaleh { stroke: #34d399; }
    }
  </style>
  <path
    class="hasaleh"
    d="${d}"
    fill="none"
    stroke="#046b4a"
    stroke-width="${STROKE}"
    stroke-linejoin="round"
  />
</svg>
`;

fs.writeFileSync(OUTPUT, svg);
console.log(`profile: ${BANDS} bands, max radius ${maxRadius.toFixed(3)}, height ${(yMax - yMin).toFixed(3)}`);
console.log(`wrote app/icon.svg  ${svg.length} bytes`);
