/**
 * Converts the site's binary mesh back into a plain OBJ.
 *
 *   npm run obj
 *
 * `public/hasaleh.mesh` is a custom format only this app can read, so this exists
 * to get the *processed* model back out into something Blender, Rhino, Cinema 4D
 * or a 3D printer will open.
 *
 * What that gives you over the raw scan in `hasaleh media/hasaleh scan.obj`:
 *   - ~33k triangles instead of 265k, and about a tenth the file size
 *   - the scan's 2.31° lean straightened onto the vertical axis
 *   - centred on the origin and scaled to a known height
 *   - smooth vertex normals recomputed after decimation
 *
 * The raw scan remains the source of truth. Re-run `npm run model` first if you
 * have rescanned.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const MESH = path.join(ROOT, 'public', 'hasaleh.mesh');
/** Written beside the original scan, so the 3D assets stay together. */
const OUTPUT = path.resolve(ROOT, '../hasaleh media/hasaleh-processed.obj');

/** Decimal places. Six is well past what a 33k-triangle mesh can carry. */
const PRECISION = 6;

function readMesh(file) {
  const buffer = fs.readFileSync(file);
  if (buffer.toString('ascii', 0, 4) !== 'HSLH') throw new Error('not a Hasaleh mesh');
  const version = buffer.readUInt32LE(4);
  if (version !== 2) throw new Error(`unsupported mesh version ${version}`);

  const vertexCount = buffer.readUInt32LE(8);
  const indexCount = buffer.readUInt32LE(12);
  const indexBytes = buffer.readUInt32LE(40);

  const HEADER = 64;
  const floats = vertexCount * 3;
  // Read field by field: the Buffer's byteOffset is not guaranteed to be aligned
  // for a typed-array view.
  const positions = new Float32Array(floats);
  for (let i = 0; i < floats; i++) positions[i] = buffer.readFloatLE(HEADER + i * 4);

  const normalsAt = HEADER + floats * 4;
  const normals = new Float32Array(floats);
  for (let i = 0; i < floats; i++) normals[i] = buffer.readFloatLE(normalsAt + i * 4);

  const indicesAt = normalsAt + floats * 4;
  const indices = new Uint32Array(indexCount);
  for (let i = 0; i < indexCount; i++) {
    indices[i] =
      indexBytes === 2 ? buffer.readUInt16LE(indicesAt + i * 2) : buffer.readUInt32LE(indicesAt + i * 4);
  }

  return { positions, normals, indices, vertexCount, indexCount };
}

const { positions, normals, indices, vertexCount, indexCount } = readMesh(MESH);

const n = (value) => value.toFixed(PRECISION).replace(/\.?0+$/, '') || '0';

const lines = [
  '# Hasaleh — processed mesh',
  '#',
  '# Generated by scripts/mesh-to-obj.mjs from public/hasaleh.mesh, which is itself',
  '# built from "hasaleh media/hasaleh scan.obj" by scripts/prepare-model.mjs.',
  '#',
  '# Decimated by vertex clustering, lean straightened onto +Y, centred on the',
  '# origin, scaled to 2.1 units tall, smooth normals recomputed.',
  `# ${vertexCount} vertices, ${indexCount / 3} triangles.`,
  '#',
  'o Hasaleh',
];

for (let i = 0; i < vertexCount; i++) {
  const o = i * 3;
  lines.push(`v ${n(positions[o])} ${n(positions[o + 1])} ${n(positions[o + 2])}`);
}
for (let i = 0; i < vertexCount; i++) {
  const o = i * 3;
  lines.push(`vn ${n(normals[o])} ${n(normals[o + 1])} ${n(normals[o + 2])}`);
}
// OBJ indices are 1-based. `v//vn` — no texture coordinates, the scan has none.
for (let i = 0; i < indexCount; i += 3) {
  const a = indices[i] + 1;
  const b = indices[i + 1] + 1;
  const c = indices[i + 2] + 1;
  lines.push(`f ${a}//${a} ${b}//${b} ${c}//${c}`);
}

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, `${lines.join('\n')}\n`);

const bytes = fs.statSync(OUTPUT).size;
console.log(`wrote ${path.relative(process.cwd(), OUTPUT)}`);
console.log(`  ${vertexCount.toLocaleString()} vertices, ${(indexCount / 3).toLocaleString()} triangles`);
console.log(`  ${(bytes / 1e6).toFixed(2)} MB`);
